### ISSUE TITLE
Typos and/or strange wording and/or formatting

### ISSUE THREAD

**Issue by ebalke** [cmukgb/ctfws#5]
"These are the preliminary rules for the Spring 2016 game of Capture the Flag with Stuff." - either remove this or change spring to fall to avoid confusing freshman

verb missing? " If they each captive of that captor must remain stationary for as long as the captor remains within their line of sight" V.D.4

for blue potion, if a captor captures two players using the key phrase "obay", do they both share the potion and go to jail or does one captive take the potion and the captor takes the other captive? in III.D.3 it is unclear "III.D.3. A player may capture two people simultaneously with one invocation of the potion's ability. They must be simultaneously tagged when the player says "obey". Both enemies become the player's captive."

VI,4,a i feel would be easier red if indented in so it was under VI4. same with VI5 a and b

**Comment by timparenti** [comment]
> "These are the preliminary rules for the Spring 2016 game of Capture the Flag with Stuff." - either remove this or change spring to fall to avoid confusing freshman

Fixed in c211aa37f874a4439cca374b622d2d9770f258ff.

> verb missing?

This must have gotten dropped in transcription from the working copy.  Fixed in 24d6a4a3eabaa070086dedfd7c2ab337c32dcd99.

> VI,4,a i feel would be easier red if indented in so it was under VI4. same with VI5 a and b

The current formatting is consistent with other subrules.

**Comment by ebalke** [comment]
"The current formatting is consistent with other subrules."

then maybe we should change that for all the rules to improve readability. especially for the new items, having everything in one block made it difficult for me to understand them.

**Comment by timparenti** [comment]
Agreed, and addressed in a648e39ff6eaaa592ec3f5fcdffed7dcfd337771.
