### ISSUE TITLE
 Doc Arnold's Belt of Many Places at Once

### ISSUE THREAD

**Issue by ebalke** [cmukgb/ctfws#6]
V.D.2. A player wearing Doc Arnold's Belt may have up to three captives at once. They may attempt to capture further captives beyond their first.
V.D.3. Once any captures have been made, the player must lead the captives directly to jail as normal. On their way, the player may deviate from their route only in the manner described below in V.D.4.

This seems slightly unclear to me. Is the intent that you can only capture one person at a time and then go out for more? if so, suggest V.D.3 change to "Once the first capture has been made" bc as i understand it from the way this is written, i could capture two at once, then go out for a third.

also "V.D.4.a. A captor wearing Doc Arnold's belt may not use the key phrase again if they have not brought a new captive back to their waiting captive(s) since the last time they used the key phrase."
I think this would be more readable if reversed. like "If a captor wearing Doc Arnold;s belt fails to return to their waiting captive(s) with a new captive, they may not use the key phase again and must return directly to jail with their captive(s)"

**Comment by skyejinx** [comment]
Resolved
